version: '3'
services:
  raspifancontroller:
    container_name: raspifancontroller
    user: "64198:997" # group 997 is necessary to access the GPIO pins
    environment:
      - AppSettings__UpperTemperatureThreshold=70
      - AppSettings__LowerTemperatureThreshold=55
    image: mu88/raspifancontroller:latest
    ports:
      - 127.0.0.1:5000:8080
    volumes:
      - /sys/class/thermal/thermal_zone0:/sys/class/thermal/thermal_zone0 # CpuTemperature needs this
    devices:
      - /dev/gpiomem