name: CI

on:
  push:
  pull_request:

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'
    - name: Install dependencies
      run: dotnet restore
    - name: Begin Sonar scan
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /k:mu88_RaspiFanController /o:mu88 /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io /d:sonar.cs.opencover.reportsPaths=Tests/coverage.opencover.xml
    - name: .NET Build
      run: dotnet build --no-restore
    - name: Test and collect coverage
      run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: End Sonar scan
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        file: RaspiFanController/Dockerfile