name: GitHub Actions Checks

on:
  push:
    paths:
      - '.github/**'

jobs:
  gha-checks:
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    uses: mu88/common/.github/workflows/gha-checks.yml@d95f73b94fe1a68e38caa30a7f33d6ee095368a9 # main
